### ISSUE TITLE
 Task :zendesk2:compileReleaseKotlin FAILED

### ISSUE THREAD

**Issue by ChanakaWeerasinghe** [KohlsAdrian/zendesk2#35]
Task :zendesk2:compileReleaseKotlin FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 597 actionable tasks: 8 executed, 589 up-to-date
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/Zendesk2
Chat.kt: (213, 34): Unresolved reference: agents
[   +1 ms] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (10, 19): Unresolved reference: firebase
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (11, 19): Unresolved reference: firebase
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (17, 36): Unresolved reference: FirebaseMessagingService
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (20, 5): 'onNewToken' overrides nothing
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (24, 5): 'onMessageReceived' overrides nothing
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (24, 51): Unresolved reference: RemoteMessage
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (35, 66): Type mismatch: inferred type is MyFirebaseMessagingService but Context was expected
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (43, 61): Type mismatch: inferred type is MyFirebaseMessagingService but Context was expected
[        ] e:
/Users/ieebl/flutter2/.pub-cache/hosted/pub.dartlang.org/zendesk2-1.6.0+1/android/src/main/kotlin/br/com/adriankohls/zendesk2/fcm/MyFi
rebaseMessagingService.kt: (65, 21): Unresolved reference: getSystemService
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':zendesk2:compileReleaseKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 15s
[ +366 ms] Running Gradle task 'assembleRelease'... (completed in 16.2s)
[   +3 ms] "flutter apk" took 17,204ms.
[   +4 ms] Gradle task assembleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:464:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:231:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

**Comment by savy-91** [comment]
@ChanakaWeerasinghe You can try to use the fork referenced in this PR that was unfortunately closed without being merged, if you want to stay on 1.6.x https://github.com/KohlsAdrian/zendesk2/pull/34

Otherwise you'll have to upgrade to 2.0.0+1 but that has breaking changes.

**Comment by KohlsAdrian** [comment]
First things first, as you are already using a null-safety version, I encourage you to get the latest version, it has minimum breaking changes that is something you can fix in an hour.

Second: I think you are using an outdated Kotlin version, recommended Kotlin ext.version is `1.5.21` in both your android app and project build.gradle

Third: Latest gradle version stable with Android is `6.1.1` that you should be using in your `gradle-wrapper.properties`


`gradle-wrapper.properties`:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https://services.gradle.org/distributions/gradle-6.7.1-all.zip
```

Observation: 

Gradle 7.0.0+ you should always make a debug, profile builds so you can make a release build (annoying bug)

What you have to always do on this major version to have success in this order
```
flutter build appbundle --debug
flutter build appbundle --profile
flutter build appbundle --release
```
Otherwise this order, your build always breaks
