### ISSUE TITLE
Critical Bug when Agent request rating

### ISSUE THREAD

**Issue by rupas385** [KohlsAdrian/zendesk2#37]
Hi,

when agent request a rating from Zendesk Panel the app crashed with this error.

type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'

 ChatLogType.fromJson (package:zendesk2/chat2/model/chat_provider_model.dart:282:44)
#1 new ChatLog.fromJson (package:zendesk2/chat2/model/chat_provider_model.dart:169:43)
#2 new ChatProviderModel.fromJson.<anonymous closure> (package:zendesk2/chat2/model/chat_provider_model.dart:30:62)

**Comment by KohlsAdrian** [comment]
Please provide the full log

**Comment by rupas385** [comment]
Hi this is the relevant part of log. When agent request rating the app crash because zendesk sent less info, and your provider resfresh and missing required data
